name: flutter_network_image
description: Flutter netwrok image provider with retry option.
version: 0.0.2
homepage: https://github.com/GeekAbdelouahed/flutter_network_image

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter: